apiVersion: v1
kind: ConfigMap
metadata:
  name: bipins-ai-config
  namespace: bipins-ai
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "http://+:8080"
  Qdrant__Endpoint: "http://qdrant:6333"
  Qdrant__CollectionName: "default"
  Qdrant__VectorSize: "1536"
